module AllNames exposing (..)


-- list of all possible names
allNames: List String
allNames = [
    "Maryanna Amick",
    "Cherelle Gallagher",
    "Juliet Mcclintic",
    "Elodia Canale",
    "Esteban Rucker",
    "Williams Bergeron",
    "Fannie Emond",
    "Rosette Jardine",
    "Tisha Drinnon",
    "Cole Biery",
    "Natisha Borum",
    "Jerrold Pieper",
    "Izetta Stigall",
    "Rory Lasch",
    "Jeanette Streight",
    "Jacob Felkins",
    "Dyan Vangorder",
    "Criselda Tinner",
    "Donnell Levy",
    "Nicola Levingston",
    "Anglea Buchta",
    "Mee Souther",
    "Louvenia Ashline",
    "Angelyn Steinberg",
    "Thora Breslin",
    "Donn Dyches",
    "Kathe Papageorge",
    "Debi Luck",
    "Vanita Skow",
    "Larae Cribb",
    "Chase Dyer",
    "Raleigh Bober",
    "Edmund Summer",
    "Gregorio Pare",
    "Geoffrey Prahl",
    "Shari Tierney",
    "Jammie Dimaggio",
    "Kina Eslinger",
    "Rachael Langlois",
    "Delmar Nerney",
    "Sharan Barros",
    "Vanda Ells",
    "Haywood Caviness",
    "Garfield Neubauer",
    "Ariana Albin",
    "Darnell Conely",
    "Lida Backes",
    "Tonita Reyna",
    "Eilene Hogg",
    "Ciera Haberle"
    ]
